home/urls.py
from django.urls import path,include
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    path('关于我们/', TemplateView.as_view(template_name='about_us.html'), name='about_us'),
    path('隐私和条款/', TemplateView.as_view(template_name='T-P.html'), name='T-P'),
    path('联系我们/', views.contact_view, name='contact_us'),

    path('搜索/',views.SearchAll,name='searchAll'),
    path('',views.MainView,name="homepage"),

    path('通讯/',views.TongXun,name="tongxun"),
    path('通讯/<int:tongxun_id>',views.TongXunDetail,name="tongxundetail"),

    path('书讯/',views.ShuXun,name="shuxun"),
    path('书讯/<int:shuxun_id>',views.ShuXunDetail,name="shuxundetail"),

    path('书评/',views.ShuPing,name="shuping"),
    path('书评/<int:shuping_id>',views.ShuPingDetail.as_view(),name="shupingdetail"),

    path('观点/',views.GuanDian,name="guandian"),
    path('观点/<int:guandian_id>',views.GuanDianDetail.as_view(),name="guandiandetail"),

    path('文艺/',views.WenYi,name="wenyi"),
    path('文艺/<int:wenyi_id>',views.WenYiDetail.as_view(),name="wenyidetail"),

    path('视频/',views.ShiPing,name="shiping"),
    path('视频/<int:shiping_id>',views.ShiPingDetail.as_view(),name="shipingdetail"),

    path('问答/',views.WenDa,name="wenda"),
    path('问答/搜索结果/',views.WenDaSearch,name="wendasearch"),
    path('问答/提交问题/',views.WenDaAddQuestion,name="wendaaddquestion"),
    path('问答/<int:wenda_id>',views.WenDaDetail.as_view(),name="wendadetail"),

    path('经训/', views.JingXun, name='jingxun'),
    path('经训/所有章节/<int:经训_id>/', views.show_all_chapters, name='show_all_chapters'),
    path('经训/内容/<int:章节_id>/', views.JingXuncontent, name='jingxundetail'), 
    path('经训/搜索结果/', views.search, name='search'),
    path('书库/', views.ShuKu, name='shuku'),
    path('书库/<int:shuku_id>/', views.ShuKucontent, name='detail'),
    path('古籍/', views.GuJi, name='guji'),
    path('古籍/<int:guji_id>/', views.GuJicontent, name='gujidetail'),
    path('论文/', views.LunWen, name='lunwen'),
    path('论文/<int:lunwen_id>/', views.LunWencontent, name='lunwendetail'),
    path('译林/', views.YiLing, name='yiling'),
    path('译林/<int:yiling_id>/', views.YiLingcontent, name='yilingdetail'),

    path('文史/',views.WenShi,name="wenshi"),
    path('文史/<int:wenshi_id>',views.WenShiDetail.as_view(),name="wenshidetail"),
]

shuwei/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('home.urls','home'),namespace='home')),
    path('admin_task/',include(('admin_task.urls','admin_task'),namespace='admin_task'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/frontend/书评/detail.html
{% extends 'base.html' %}
{% load bootstrap_icons %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row mt-3">
        <div class="col ">
            <h1 >
                {{ shuping.标题 }}
            </h1>
            <div class="row ">
                <div class="col">
                    <h5 class="  text-muted" >
                        作者：{{shuping.书评作者}}
                    </h5>
                    <h5 class=" text-muted" >
                        书籍作者:{{shuping.书籍作者 }}
                    </h5>
                </div>
                <div class="col text-right">
                    <h5 class=" text-md-right text-muted">
                        更新时间<br />
                        {{ shuping.更新时间|date:'Y' }}年{{ shuping.更新时间|date:'m' }}月{{ shuping.更新时间|date:'d' }}日
                    </h5>
                </div>
            </div>
            <hr class="hr-content mt-0">
        </div>
    </div>
    <div class="row mb-2 ">
        {% if shuping.图片 %}
        <img class="fixed-image" src="{{ MEDIA_URL }}{{ shuping.图片 }}" >
        {% else %}
        <img class="fixed-image" src="{% static 'images/default-placeholder.png' %}">
        {% endif %}
    </div>
    <div class="row mb-4 -4 pb-4">
        <div class="col">
            <div class="row">
                <p>
                    {{shuping.书评内容|safe}}
                </p>
                
            </div>
          <div class="row mt-3 mb-3 border-bottom">
                 <div class="col mt-3 mb-3">
                     <h4><strong>评论区</strong></h4>
                 </div>
                 <div class="col mt-3 mb-3 text-right">
                     {% bs_icon 'chat-right-dots' %}{{comments.count}}
                 </div>
            </div>
            {% for comment in comments %}
            <div class="row border mt-3 mb-3 p-3">
                <div class="col">{{comment.评论}}</div>
                <div class="col text-right text-muted">{{comment.发布时间|date:'Y' }}年{{comment.发布时间|date:'m' }}月{{comment.发布时间|date:'d' }}日 {{comment.发布时间|date:'h:i:s' }}</div>

            </div>
            {% endfor %}
            <div class="row">
                <form method="POST" >
                    <div class="form-floating">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-outline-dark" type="submit">发表</button>
                    </div>
                </form>
            </div>
        </div>

        <div class="col-4 ml-2 d-none d-md-block">
          <div class="row border rounded pb-2 sticky-scroll">
            <div class="row no-gutters p-2 bg-light align-items-stretch mb-2">
                <h4>其他书评</h4>
            </div>
            {% for obj in all_书评 %}
            <a href ="{% url 'home:shuxundetail' obj.id %}" >
                <div class="card card-img-horizontal border rounded mb-2" style="flex-direction:row;">
                    {% if obj.图片 %}
                    <img class="w-100 align-middle" src="{{ MEDIA_URL }}{{ obj.图片 }}">
                    {% else %}
                    <img class="w-100 align-middle" src="{% static 'images/default-placeholder.png' %}">
                    {% endif %}
                    <div class="card-body p-2">
                        <small class="text-muted">标题</small>
                        <h5 class="card-title font-weight-bold">{{obj.标题|truncatechars:20}}</h5>
                        <small class="text-muted card-date">{{obj.更新时间|date:'Y-m-d h:i:s' }}</small>
                    </div>
                </div>
            </a>
          {% endfor %}
            <a class="nav-link" href="{% url 'home:shuxun' %}">
                <div class=" w-100 btn btn-outline-dark bg-light mb-2">
                    更多书讯
                </div>
            </a>
          </div>
        </div>
    </div>
</div>
{% endblock %}

templates/frontend/书评/main.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap_icons %}
{% block content %}
<div class="container">
    <div class="row mb-4 mt-4">
        <h2>
            <strong>书评列表</strong>
        </h2>
    </div>
    <div class="row mb-4 mt-4">
         {% for obj in all_书评 %}
        <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-3">
            <a href="{% url 'home:shupingdetail' obj.id %}" class="text-decoration-none">
                <div class="card border h-100 bg-light rounded">
                    {% if obj.图片 %}
                    <img class="card-img-top card-img h-50" src="{{ MEDIA_URL }}{{ obj.图片 }}">
                    {% else %}
                    <img class="card-img-top card-img h-50" src="{% static 'images/default-placeholder.png' %}">
                    {% endif %}
                    <div class="card-body p-3">
                        <small class="text-muted">标题</small>
                        <h4 class="card-title font-weight-bold">{{ obj.标题 |truncatechars:14 }}</h4>
                        <small class="text-muted">内容</small>
                        <div class="fs-6 fw-light mb-4">
                            {{ obj.书评内容|striptags|safe|truncatechars:25 }}
                            {% if obj.书评内容|length > 25 %}
                            <small class="text-muted">更多</small>
                            {% endif %}
                        </div>
                        <div class="card-date">
                            <small class="text-muted">
                                {{ obj.更新时间|date:'Y-m-d h:i:s' }}
                            </small>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}