home/urls.py
from django.urls import path,include
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    path('关于我们/', TemplateView.as_view(template_name='about_us.html'), name='about_us'),
    path('隐私和条款/', TemplateView.as_view(template_name='T-P.html'), name='T-P'),
    path('联系我们/', views.contact_view, name='contact_us'),

    path('搜索/',views.SearchAll,name='searchAll'),
    path('',views.MainView,name="homepage"),

    path('通讯/',views.TongXun,name="tongxun"),
    path('通讯/<int:tongxun_id>',views.TongXunDetail,name="tongxundetail"),

    path('书讯/',views.ShuXun,name="shuxun"),
    path('书讯/<int:shuxun_id>',views.ShuXunDetail,name="shuxundetail"),

    path('书评/',views.ShuPing,name="shuping"),
    path('书评/<int:shuping_id>',views.ShuPingDetail.as_view(),name="shupingdetail"),

    path('观点/',views.GuanDian,name="guandian"),
    path('观点/<int:guandian_id>',views.GuanDianDetail.as_view(),name="guandiandetail"),

    path('文艺/',views.WenYi,name="wenyi"),
    path('文艺/<int:wenyi_id>',views.WenYiDetail.as_view(),name="wenyidetail"),

    path('视频/',views.ShiPing,name="shiping"),
    path('视频/<int:shiping_id>',views.ShiPingDetail.as_view(),name="shipingdetail"),

    path('问答/',views.WenDa,name="wenda"),
    path('问答/搜索结果/',views.WenDaSearch,name="wendasearch"),
    path('问答/提交问题/',views.WenDaAddQuestion,name="wendaaddquestion"),
    path('问答/<int:wenda_id>',views.WenDaDetail.as_view(),name="wendadetail"),

    path('经训/', views.JingXun, name='jingxun'),
    path('经训/所有章节/<int:经训_id>/', views.show_all_chapters, name='show_all_chapters'),
    path('经训/内容/<int:章节_id>/', views.JingXuncontent, name='jingxundetail'), 
    path('经训/搜索结果/', views.search, name='search'),
    path('书库/', views.ShuKu, name='shuku'),
    path('书库/<int:shuku_id>/', views.ShuKucontent, name='detail'),
    path('古籍/', views.GuJi, name='guji'),
    path('古籍/<int:guji_id>/', views.GuJicontent, name='gujidetail'),
    path('论文/', views.LunWen, name='lunwen'),
    path('论文/<int:lunwen_id>/', views.LunWencontent, name='lunwendetail'),
    path('译林/', views.YiLing, name='yiling'),
    path('译林/<int:yiling_id>/', views.YiLingcontent, name='yilingdetail'),

    path('文史/',views.WenShi,name="wenshi"),
    path('文史/<int:wenshi_id>',views.WenShiDetail.as_view(),name="wenshidetail"),
]

shuwei/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('home.urls','home'),namespace='home')),
    path('admin_task/',include(('admin_task.urls','admin_task'),namespace='admin_task'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/frontend/问答/detail.html
{% extends 'base.html' %}
{% load bootstrap_icons %}
{% block content %}
<div class="container ">
    <div class="row mb-4">
        <div class="col">
            <div class="row mb-4 mt-4">
                <h2>
                    问题&nbsp{{wenda.序号}}:<strong> {{wenda.标题}}</strong>
                </h2>
            </div>
            <hr class="mt-2 mb-4" />
            <div class="row mb-4 mt-4">
                <h2>
                    答案:
                </h2>
                <h3>
                    <strong>
                        {% if wenda.参考问答 %}
                        {{wenda.参考问答项目.答案|safe}}
                        {% else %}
                        {{wenda.答案|safe}}
                        {% endif %}
                    </strong>
                </h3>
            </div>
            <div class="row mt-3 mb-3 border-bottom">
                <div class="col mt-3 mb-3">
                    <h4><strong>评论区</strong></h4>
                </div>
                <div class="col mt-3 mb-3 text-right">
                    {% bs_icon 'chat-right-dots' %}{{comments.count}}
                </div>
            </div>
            {% for comment in comments %}
            <div class="row border mt-3 mb-3 p-3">
                <div class="col">{{comment.评论}}</div>
                <div class="col text-right text-muted">{{comment.发布时间|date:'Y' }}年{{comment.发布时间|date:'m'}}月{{comment.发布时间|date:'d' }}日 {{comment.发布时间|date:'h:i:s' }}</div>

            </div>
            {% endfor %}
            <div class="row">
                <form method="POST">
                    <div class="form-floating">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-outline-dark" type="submit">发表</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-3 ml-2   d-none d-md-block">
            <div class="row border rounded pb-2 sticky-scroll">
                <div class="row no-gutters p-2 bg-light align-items-stretch mb-2">
                    <h4>其他问答</h4>
                </div>
                {% for obj in all_问答 %}
                <div class="row mb-4 mt-4">
                    <a href="{% url 'home:wendadetail' obj.id %}">
                        <div class="card border bg-light h-100 rounded w-100">
                            <div class="card-body pt-2 pb-1">
                                <div class="row">
                                    <div class="text-center text-white bg-secondary p-1 status-tab w-25 ">
                                        {{obj.序号}}
                                    </div>
                                    <h4 class="mt-2 card-title font-weight-bold">问题: {{obj.标题 }}</h4>
                                    <small class="text-muted">{{obj.更新时间|date:'Y' }}年{{obj.更新时间|date:'m'}}月{{obj.更新时间|date:'d' }}日 {{obj.更新时间|date:'h:i:s' }}</small>
                                    <div class="text-right ">{% bs_icon 'chat-right-dots' %}{{obj.comment_no}}</div>
                                </div>


                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
                <a class="nav-link" href="{% url 'home:wenda' %}">
                    <div class=" w-100 btn btn-outline-dark bg-light mb-2">
                        更多问答
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>


</div>
{% endblock %}

templates/frontend/问答/main.html
{% extends 'base.html' %}
{% load bootstrap_icons %}
{% block content %}
<div class="container">
    <div class="row mb-4 mt-4">
        <div class="col-12 col-md-6">
            <h2>
                <strong>问答列表</strong>
            </h2>
        </div>
        <div class="col-12 col-md-6 mt-3 mt-md-0">
            <form action="{% url 'home:wendasearch' %}" class="form-inline justify-content-center justify-content-md-end" method="GET">
                <div class="input-group">
                    <input class="form-control" name="keyword" type="text" placeholder="题目关键词"/>
                    <div class="input-group-append">
                        <button class="btn " type="submit">{% bs_icon 'search' size='1x' %}</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row add-question-section mt-4 mb-4 ml-4 mr-4 p-4 border border-2 rounded">
        <div class="col-12 text-center mb-3">
            <h3><strong>提出问题</strong></h3>
        </div>
        <div class="">
            <form action="{% url 'home:wendaaddquestion' %}" class="form-inline text-center" method="POST">
                {% csrf_token %}
                <div class="input-group text-center" style="">
                    <input class="form-control " id="question" name="question" type="text" placeholder="问题" />
                    <div class="input-group-append">
                        <button class="btn" type="submit">提交</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    
    <hr class="mt-2 mb-4"/>
    {% if keyword %}
    <div class="row ml-2">
        <div class="col"><h3>搜索结果: {{ keyword }}</h3></div>
        <div class="col-6 col-md-2 text-right">
            <a href="{% url 'home:wenda' %}">
                <div class="text-center text-white bg-secondary p-1 mx-auto status-tab">显示全部</div>
            </a>
        </div>
    </div>
    {% endif %}
    {% for obj in all_问答 %}
    <div class="row mb-4 mt-4">
        <a href="{% url 'home:wendadetail' obj.id %}">
            <div class="card border bg-light h-100 rounded">
                <div class="card-body p-4">
                    <div class="row">
                        <div class="col-4 col-md-2">
                            <div class="text-center text-white bg-secondary p-1 mx-auto status-tab">
                                {{ obj.序号 }}
                            </div>
                        </div>
                        <div class="col-8 col-md-4 mt-3 mt-md-0">
                            <h4>{{ obj.更新时间|date:'Y-m-d H:i:s' }}</h4>
                        </div>
                        <div class="col-12 col-md-6 mt-3 mt-md-0">
                            <h4 class="card-title font-weight-bold">问题: {{ obj.标题 }}</h4>
                        </div>
                        <div class="col-12 mt-3">
                            <div class="text-right">
                                {% bs_icon 'chat-right-dots' %}
                                {{ obj.comment_no }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    </div>
    {% endfor %}
</div>
{% endblock %}