home/urls.py
from django.urls import path,include
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    path('关于我们/', TemplateView.as_view(template_name='about_us.html'), name='about_us'),
    path('隐私和条款/', TemplateView.as_view(template_name='T-P.html'), name='T-P'),
    path('联系我们/', views.contact_view, name='contact_us'),

    path('搜索/',views.SearchAll,name='searchAll'),
    path('',views.MainView,name="homepage"),

    path('通讯/',views.TongXun,name="tongxun"),
    path('通讯/<int:tongxun_id>',views.TongXunDetail,name="tongxundetail"),

    path('书讯/',views.ShuXun,name="shuxun"),
    path('书讯/<int:shuxun_id>',views.ShuXunDetail,name="shuxundetail"),

    path('书评/',views.ShuPing,name="shuping"),
    path('书评/<int:shuping_id>',views.ShuPingDetail.as_view(),name="shupingdetail"),

    path('观点/',views.GuanDian,name="guandian"),
    path('观点/<int:guandian_id>',views.GuanDianDetail.as_view(),name="guandiandetail"),

    path('文艺/',views.WenYi,name="wenyi"),
    path('文艺/<int:wenyi_id>',views.WenYiDetail.as_view(),name="wenyidetail"),

    path('视频/',views.ShiPing,name="shiping"),
    path('视频/<int:shiping_id>',views.ShiPingDetail.as_view(),name="shipingdetail"),

    path('问答/',views.WenDa,name="wenda"),
    path('问答/搜索结果/',views.WenDaSearch,name="wendasearch"),
    path('问答/提交问题/',views.WenDaAddQuestion,name="wendaaddquestion"),
    path('问答/<int:wenda_id>',views.WenDaDetail.as_view(),name="wendadetail"),

    path('经训/', views.JingXun, name='jingxun'),
    path('经训/所有章节/<int:经训_id>/', views.show_all_chapters, name='show_all_chapters'),
    path('经训/内容/<int:章节_id>/', views.JingXuncontent, name='jingxundetail'), 
    path('经训/搜索结果/', views.search, name='search'),
    path('书库/', views.ShuKu, name='shuku'),
    path('书库/<int:shuku_id>/', views.ShuKucontent, name='detail'),
    path('古籍/', views.GuJi, name='guji'),
    path('古籍/<int:guji_id>/', views.GuJicontent, name='gujidetail'),
    path('论文/', views.LunWen, name='lunwen'),
    path('论文/<int:lunwen_id>/', views.LunWencontent, name='lunwendetail'),
    path('译林/', views.YiLing, name='yiling'),
    path('译林/<int:yiling_id>/', views.YiLingcontent, name='yilingdetail'),

    path('文史/',views.WenShi,name="wenshi"),
    path('文史/<int:wenshi_id>',views.WenShiDetail.as_view(),name="wenshidetail"),
]

shuwei/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('home.urls','home'),namespace='home')),
    path('admin_task/',include(('admin_task.urls','admin_task'),namespace='admin_task'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from ckeditor.fields import RichTextField
from sorl.thumbnail import ImageField
from django.utils.html import strip_tags
# Create your models here.
# 通讯
class 通讯(models.Model):
    标题 = models.CharField(max_length=150)
    内容 = RichTextField(blank=True,null=True)
    更新时间 = models.DateTimeField(auto_now=True)
    发布状态 = models.BooleanField(default=False)
    资源 = models.CharField(max_length=200,null=True,blank=True,default="无资源信息")
    作者 = models.CharField(max_length=200,null=True,blank=True,default="无作者信息")
    def __str__(self):
        return self.标题


class 书讯(models.Model):
    标题 = models.CharField(max_length=150)
    内容简介 = RichTextField(null=True,blank=True,max_length=300,default="暂无内容简介")
    作者简介 = RichTextField(null=True,blank=True,max_length=300,default="暂无作者简介")
    目录 = RichTextField(null=True,blank=True,default="暂无")
    前言 = RichTextField(null=True,blank=True,default="暂无")
    ISBN = models.CharField(max_length=30,null=True,blank=True,default="暂无")
    作者 = models.CharField(max_length=200,null=True,blank=True,default="暂无")
    出版社 = models.CharField(max_length=200,null=True,blank=True,default="暂无")
    出版年 = models.DateField(null=True,blank=True,default="暂无")
    定价 =  models.CharField(max_length=10,null=True,blank=True,default="暂无")
    页数 =  models.IntegerField(null=True,blank=True)
    装帧 = models.CharField(max_length=20,null=True,blank=True,default="暂无")
    图片 = ImageField(upload_to='images/shuxun/',blank=True,null=True)
    更新时间 = models.DateTimeField(auto_now=True)
    发布状态 = models.BooleanField(default=False)
    def __str__(self):
        return self.标题

class 书评(models.Model):
    标题 = models.CharField(max_length=150)
    书籍作者 =models.CharField(max_length=200,null=True,blank=True)
    书籍出版日期 = models.DateField(null=True,blank=True)
    书评内容 = RichTextField()
    更新时间 = models.DateTimeField(auto_now=True)
    书评作者 = models.CharField(max_length=200,null=True,blank=True)
    图片 = ImageField(upload_to='images/shuping/',blank=True,null=True)
    发布状态 = models.BooleanField(default=False)

    def __str__(self):
        return self.标题

class 评论_书评(models.Model):
    书评 = models.ForeignKey(书评,on_delete=models.CASCADE)
    评论 = models.CharField(max_length=200)
    通过 = models.CharField(max_length=100,default='审查中')
    发布时间 = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.评论

class 观点(models.Model):
    标题 = models.CharField(max_length=150)
    内容 = RichTextField(blank=True,null=True)
    更新时间 = models.DateTimeField(auto_now=True)
    作者 = models.CharField(max_length=200, null=True,blank=True)
    图片 = ImageField(upload_to='images/guandian/',blank=True,null=True)
    发布状态 = models.BooleanField(default=False)

    def __str__(self):
        return self.标题

class 评论_观点(models.Model):
    观点 = models.ForeignKey(观点,on_delete=models.CASCADE)
    评论 = models.CharField(max_length=200)
    通过 = models.CharField(max_length=100,default='审查中')
    发布时间 = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.评论

class 文艺(models.Model):
    标题 = models.CharField(max_length=150)
    内容 = RichTextField(blank=True,null=True)
    更新时间 = models.DateTimeField(auto_now=True)
    作者 = models.CharField(max_length=200,  null=True,blank=True)
    图片 = ImageField(upload_to='images/wenyi/',blank=True,null=True)
    发布状态 = models.BooleanField(default=False)
    def __str__(self):
        return self.标题

class 评论_文艺(models.Model):
    文艺 = models.ForeignKey(文艺,on_delete=models.CASCADE)
    评论 = models.CharField(max_length=200)
    通过 = models.CharField(max_length=100, default='审查中')
    发布时间 = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.评论


class 视频(models.Model):
    标题 = models.CharField(max_length=150)
    视频文件 = models.FileField(upload_to='videos/',blank=True,null=True)
    发布状态 = models.BooleanField(default=False)
    更新时间 = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.标题

class 评论_视频(models.Model):
    视频 = models.ForeignKey(视频,on_delete=models.CASCADE)
    评论 = models.CharField(max_length=200)
    通过 = models.CharField(max_length=100, default='审查中')
    发布时间 = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.评论

class 问答(models.Model):
    标题 = models.CharField(max_length=150)
    答案 = RichTextField(blank=True)
    序号 = models.CharField(max_length=4,blank=True)
    参考问答 = models.BooleanField(default=False)
    参考问答项目= models.ForeignKey('self',null=True,blank=True,default=None,on_delete=models.CASCADE)
    更新时间 = models.DateTimeField(auto_now=True)
    发布状态 = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if(self.参考问答==True):
            self.答案=''
        super().save(*args, **kwargs)
        self.序号='{0:04d}'.format(self.id)
        super().save(*args, **kwargs)

    def __str__(self):
        title = self.序号 +" - "+ self.标题 +"\n答案:" + strip_tags(self.答案)
        return title

class 提问_问答(models.Model):
    标题 = models.CharField(max_length=150)
    通过 = models.BooleanField(default=False)
    发布时间 = models.DateTimeField(auto_now=True)

class 评论_问答(models.Model):
    问答 = models.ForeignKey(问答,on_delete=models.CASCADE)
    评论 = models.CharField(max_length=200)
    通过 = models.CharField(max_length=100, default='审查中')
    发布时间 = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.评论

class 译林(models.Model):
    标题 = models.CharField(max_length=150)
    译文作者 = models.CharField(max_length=100, null=True, blank=True)
    更新时间 = models.DateTimeField(auto_now=True)
    原文标题 = models.CharField(max_length=150)
    译文内容 = RichTextField(blank=True,null=True)
    原文作者 = models.CharField(max_length=100, null=True, blank=True)
    原文出版日期 = models.DateField(null=True,blank=True)
    图片 = ImageField(upload_to='images/yiling/', blank=True, null=True)
    发布状态 = models.BooleanField(default=False)

class 文史(models.Model):
    标题 = models.CharField(max_length=150)
    内容 = RichTextField(blank=True, null=True)
    更新时间 = models.DateTimeField(auto_now=True)
    作者 = models.CharField(max_length=200, null=True, blank=True)
    图片 = ImageField(upload_to='images/wenshi/', blank=True, null=True)
    资源 = models.CharField(max_length=200, null=True, blank=True)
    发布状态 = models.BooleanField(default=False)
    def __str__(self):
        return self.标题
    
class 评论_文史(models.Model):
    文史 = models.ForeignKey(文史, on_delete=models.CASCADE)
    评论 = models.CharField(max_length=200)
    通过 = models.CharField(max_length=100, default='审查中')
    发布时间 = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.评论


class 论文(models.Model):
    标题 = models.CharField(max_length=150)
    作者 = models.CharField(max_length=200, null=True, blank=True)
    更新时间 = models.DateTimeField(auto_now=True)
    文档 = models.FileField(upload_to='pdf/lunwen/', default='null', null=True)
    发布状态 = models.BooleanField(default=False)

class 经训(models.Model):
    标题 = models.CharField(max_length=150)
    图片 = ImageField(upload_to='images/jingxun/', blank=True, null=True)

    更新时间 = models.DateTimeField(auto_now=True)
    发布状态 = models.BooleanField(default=False)

class 章节_经训(models.Model):
    经训 = models.ForeignKey(经训, on_delete=models.CASCADE)
    章节 = models.CharField(max_length=150)
    内容 = RichTextField()

class 古籍(models.Model):
    标题 = models.CharField(max_length=150)
    作者 = models.CharField(max_length=200, null=True, blank=True)
    更新时间 = models.DateTimeField(auto_now=True)
    文档 = models.FileField(upload_to='pdf/guji/')
    发布状态 = models.BooleanField(default=False)

class 书库(models.Model):
    标题 = models.CharField(max_length=150)
    作者 = models.CharField(max_length=200, null=True, blank=True)
    更新时间 = models.DateTimeField(auto_now=True)
    文档 = models.FileField(upload_to='pdf/shuku/')
    作者简介 =  RichTextField(null=True,blank=True,default="暂无")
    内容简介 =  RichTextField(null=True,blank=True,default="暂无")
    出版日期 = models.DateField(null=True,blank=True,default="暂无")
    图片 = ImageField(upload_to='images/shuku/', default='null', null=True)
    ISBN = models.CharField(max_length=30)
    发布状态 = models.BooleanField(default=False)


class Contact(models.Model):
    邮箱 = models.EmailField(null=False, blank=False)
    主题 = models.CharField(max_length=255)
    内容 = models.TextField(null=False, blank=False)
    def __str__(self):
        return self.邮箱

templates/frontend/经训/all_chapter.html
{% extends 'base.html' %}
{% block content %}
<div class="container justify-content-center h-100" >
    <div class="row">
        <div class="col-3 h-100 p-2 bg-light d-none d-md-block mt-4 ">
            {% include 'frontend/经训/sidebar.html' %}
        </div>
        <div class="col-md-9">
            <!-- Main content goes here -->
            <div class="p-2">
                {% include 'frontend/经训/searching.html' %}
            </div>
            <div class="row  ">
                <div class="col mb-3">
                    <div class="card">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex align-items-center " style="background-color: #DDDDDD;">
                                <div>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="12" height="16" fill="currentColor"
                                        class="bi bi-folder" viewBox="0 0 16 16">
                                        <path
                                            d="M.54 3.87.5 3a2 2 0 0 1 2-2h3.672a2 2 0 0 1 1.414.586l.828.828A2 2 0 0 0 9.828 3h3.982a2 2 0 0 1 1.992 2.181l-.637 7A2 2 0 0 1 13.174 14H2.826a2 2 0 0 1-1.991-1.819l-.637-7a1.99 1.99 0 0 1 .342-1.31zM2.19 4a1 1 0 0 0-.996 1.09l.637 7a1 1 0 0 0 .995.91h10.348a1 1 0 0 0 .995-.91l.637-7A1 1 0 0 0 13.81 4H2.19zm4.69-1.707A1 1 0 0 0 6.172 2H2.5a1 1 0 0 0-1 .981l.006.139C1.72 3.042 1.95 3 2.19 3h5.396l-.707-.707z" />
                                    </svg>
                                </div>
                                <div class="ml-2">
                                    <p class="h5 dark font-weight-bold">{{ 经训.标题 }}</p>
                                </div>
                            </li>
                            <ul class="list-group list-group-flush ml-3">
                                {% for 章节 in 章节_list %}
                                <li class="list-group-item">
                                    <a class="nav-link chapter-link custom-nav-link "
                                        href="{% url 'home:jingxundetail' 章节.id %}" data-章节="{{ 章节.章节 }}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                            fill="currentColor" class="bi bi-file-earmark-text" viewBox="0 0 16 16">
                                            <path
                                                d="M5.5 7a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5zM5 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5z" />
                                            <path
                                                d="M9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.5L9.5 0zm0 1v2A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5z" />
                                        </svg>
                                        {{ 章节.章节 }}
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/frontend/经训/content.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block content %}
<div class="d-flex flex-column justify-content-between min-vh-100" id="content-wrap">
    <div class="container mt-4">
        <div class="row">
            <div class=" col-md-3 h-100 p-2 bg-light d-none d-md-block sticky-scroll">
                {% include 'frontend/经训/sidebar.html' %}
            </div>
            <div class="col-12 col-md-9 flex-wrap">
                <div class="p-2">
                    {% include 'frontend/经训/searching.html' %}
                </div>
                <div class="about-right mb-90">
                    <div class="section-tittle mb-30 pt-30">
                        <h3>{{ 章节.章节 }}</h3>
                    </div>
                    <div class="about-prea">
                        <p class="about-pera1 mb-25">{{ 章节.内容 |safe}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

templates/frontend/经训/main.html
{% extends 'base.html' %}
{% block content %}
<div class="container justify-content-center h-100" id="content-wrap">
    <div class="row">
        <div class="col-3 h-100 p-2 bg-light d-none d-md-block mt-4 ">
            {% include 'frontend/经训/sidebar.html' %}
        </div>
        <div class="col-md-9 flex-wrap">
            <!-- 主要内容部分 -->
            <div class="p-2">
                {% include 'frontend/经训/searching.html' %}
            </div>
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3">
                {% for 经训 in all_经训 %}
                <div class="col mb-3">
                    <div class="card">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex align-items-center " style="background-color: #DDDDDD;">
                                <div>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="12" height="16" fill="currentColor"
                                        class="bi bi-folder" viewBox="0 0 16 16">
                                        <path
                                            d="M.54 3.87.5 3a2 2 0 0 1 2-2h3.672a2 2 0 0 1 1.414.586l.828.828A2 2 0 0 0 9.828 3h3.982a2 2 0 0 1 1.992 2.181l-.637 7A2 2 0 0 1 13.174 14H2.826a2 2 0 0 1-1.991-1.819l-.637-7a1.99 1.99 0 0 1 .342-1.31zM2.19 4a1 1 0 0 0-.996 1.09l.637 7a1 1 0 0 0 .995.91h10.348a1 1 0 0 0 .995-.91l.637-7A1 1 0 0 0 13.81 4H2.19zm4.69-1.707A1 1 0 0 0 6.172 2H2.5a1 1 0 0 0-1 .981l.006.139C1.72 3.042 1.95 3 2.19 3h5.396l-.707-.707z" />
                                    </svg>
                                </div>
                                <div class="ml-2">
                                    <p class="h5 dark font-weight-bold">{{ 经训.标题 }}</p>
                                </div>
                            </li>
                            <ul class="list-group list-group-flush ml-3">
                                {% for 章节 in 经训.章节_经训_set.all %}
                                {% if forloop.counter <= 6 %} <li class="list-group-item">
                                    <a class="nav-link chapter-link custom-nav-link "
                                        href="{% url 'home:jingxundetail' 章节.id %}" data-章节="{{ 章节.章节 }}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                            fill="currentColor" class="bi bi-file-earmark-text" viewBox="0 0 16 16">
                                            <path
                                                d="M5.5 7a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5zM5 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5z" />
                                            <path
                                                d="M9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.5L9.5 0zm0 1v2A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5z" />
                                        </svg>
                                        {{ 章节.章节 }}
                                    </a>
                                    </li>
                                    {% endif %}
                                    {% endfor %}
                            </ul>
                        </ul>
                        <div class="card-footer align-items-center ">
                            <a href="{% url 'home:show_all_chapters' 经训.id %} " class="text-dark  small"
                                style="text-decoration: none; color: #2283c3 !important;">显示所有章节</a>
                        </div>

                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/frontend/经训/search_results.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block content %}
<div class="d-flex flex-column justify-content-between min-vh-100" id="content-wrap">
    <div class="container mt-4">
        <div class="row">
            <div class=" col-md-3 h-100 p-2 bg-light d-none d-md-block">
                {% include 'frontend/经训/sidebar.html' %}
            </div>
            <div class="col-12 col-md-9">
                <div class="p-2">
                    {% include 'frontend/经训/searching.html' %}
                </div>
                {% for 章节 in 章节_results %}
                <div class="container mt-4">
                    <h2><a href="{% url 'home:jingxundetail' 章节.id %}">{{ 章节.章节 }}</a></h2>
                    <p>{% if 章节.内容|lower|find:keyword|default:-1 != -1 %}
                        {{ 章节.内容|highlight:keyword|safe }}
                    {% else %}
                        {{ 章节.内容|truncatechars_html:100|safe }}
                    {% endif %}</p>
                </div>
            </div>
            {% empty %}
            <p class="h1">No results found.</p>
        {% endfor %}
        </div>
    </div>

</div>

{% endblock %}

templates/frontend/经训/searching.html
<form class="d-flex w-100 border-0" role="search" action="{% url 'home:search' %}" method="GET">
    <div class="d-flex justify-content-between w-100">
        <input class="form-control me-2  " type="search" placeholder="搜索" aria-label="Search" name="keyword" 
            style="  border-top: none; border-left: none; border-right: none;">
        <button class="btn btn-outline-success  " type="submit">搜索</button>
    </div>
</form>

templates/frontend/经训/sidebar.html
<ul class="nav flex-column">
    {% for 经训 in all_经训 %}
    <li class="nav-item">
        <a class="nav-link custom-nav-link chapter-link text-dark " data-toggle="collapse" href="#collapse{{ 经训.id }}" role="button" aria-expanded="false" aria-controls="collapse{{ 经训.id }}">
            <div class="d-flex justify-content-between">
                <div>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-folder" viewBox="0 0 16 16">
                        <path d="M.54 3.87.5 3a2 2 0 0 1 2-2h3.672a2 2 0 0 1 1.414.586l.828.828A2 2 0 0 0 9.828 3h3.982a2 2 0 0 1 1.992 2.181l-.637 7A2 2 0 0 1 13.174 14H2.826a2 2 0 0 1-1.991-1.819l-.637-7a1.99 1.99 0 0 1 .342-1.31zM2.19 4a1 1 0 0 0-.996 1.09l.637 7a1 1 0 0 0 .995.91h10.348a1 1 0 0 0 .995-.91l.637-7A1 1 0 0 0 13.81 4H2.19zm4.69-1.707A1 1 0 0 0 6.172 2H2.5a1 1 0 0 0-1 .981l.006.139C1.72 3.042 1.95 3 2.19 3h5.396l-.707-.707z"/>
                    </svg>
                    {{ 经训.标题 }}
                </div>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
                </svg>
            </div>
        </a>
        <div class="collapse" id="collapse{{ 经训.id }}">
            <ul class="nav flex-column ml-3">
                {% for 章节 in 经训.章节_经训_set.all %}
                <li class="nav-item">
                    <a class="nav-link chapter-link text-dark  custom-nav-link" href="{% url 'home:jingxundetail' 章节.id %}" data-章节="{{ 章节.章节 }}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-text" viewBox="0 0 16 16">
                            <path d="M5.5 7a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5zM5 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5z"/>
                            <path d="M9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.5L9.5 0zm0 1v2A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5z"/>
                </svg>
                        {{ 章节.章节 }}
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </li>
    {% endfor %}
</ul>